// GENERATED by Scripts/gen-versions.sh from versions.env — DO NOT EDIT.
// The single source of truth for all version numbers is versions.env.

/// Version numbers surfaced to the host (CLI, status, updater).
public enum Versions {
    /// Velox release version.
    public static let velox = "0.1.0"
    /// GitHub repo (owner/name) the updater checks for new releases.
    public static let githubRepo = "mikaelhug/Velox"

    /// Guest kernel version (the VM "OS version") — built from kernel.org source.
    public static let kernelVersion = "6.12.92"
    /// containerd image running in the guest.
    public static let containerdImage = "linuxkit/containerd:ba19f64efd3331a8fd0a33e00eabd14f6ee1780e"
    /// Docker Engine (dockerd) image running in the guest.
    public static let dockerImage = "docker:27-dind"
}
