// GENERATED by Scripts/gen-versions.sh from versions.env — DO NOT EDIT.
// The single source of truth for all version numbers is versions.env.

/// Version numbers surfaced to the host (CLI, status, updater).
public enum Versions {
    /// Velox release version.
    public static let velox = "0.1.20"
    /// GitHub repo (owner/name) the updater checks for new releases.
    public static let githubRepo = "mikaelhug/Velox"
    /// Privileged-port-helper revision. The helper is (re)installed (one admin prompt) only when
    /// this changes — not on every Velox update. Bumped in versions.env when the helper changes.
    public static let porthelperRevision = "1"

    /// Guest kernel version (the VM "OS version") — built from kernel.org source.
    public static let kernelVersion = "6.18.34"
    /// Docker Engine version in the guest (Docker's official static release).
    public static let dockerVersion = "29.5.3"
}
