// GENERATED by Scripts/gen-versions.sh from versions.env — DO NOT EDIT.
// The single source of truth for all version numbers is versions.env.

/// Version numbers surfaced to the host (CLI, status, updater).
public enum Versions {
    /// Velox release version.
    public static let velox = "0.1.8"
    /// GitHub repo (owner/name) the updater checks for new releases.
    public static let githubRepo = "mikaelhug/Velox"

    /// Guest kernel version (the VM "OS version") — built from kernel.org source.
    public static let kernelVersion = "6.18.34"
    /// Docker Engine version in the guest (Docker's official static release).
    public static let dockerVersion = "29.5.3"
}
