// GENERATED by Scripts/gen-versions.sh from versions.env — DO NOT EDIT.
// The single source of truth for all version numbers is versions.env.

/// Version numbers surfaced to the host (CLI, status, updater).
enum Versions {
    /// Velox release version.
    static let velox = "0.1.0"
    /// GitHub repo (owner/name) the updater checks for new releases.
    static let githubRepo = "mikaelhug/Velox"

    /// Guest kernel image (the VM "OS version").
    static let kernelImage = "velox/kernel:6.12.59-virtiofs"
    /// containerd image running in the guest.
    static let containerdImage = "linuxkit/containerd:ba19f64efd3331a8fd0a33e00eabd14f6ee1780e"
    /// Docker Engine (dockerd) image running in the guest.
    static let dockerImage = "docker:27-dind"
}
