#!/usr/bin/env bash
# Generate Sources/VeloxCore/Support/Versions.swift from versions.env.
# Run automatically by build.sh; the generated file is also committed so the
# package always compiles from a clean checkout.
set -euo pipefail
cd "$(dirname "$0")/.."

set -a; . ./versions.env; set +a

OUT="Sources/VeloxCore/Support/Versions.swift"
cat > "$OUT" <<EOF
// GENERATED by Scripts/gen-versions.sh from versions.env — DO NOT EDIT.
// The single source of truth for all version numbers is versions.env.

/// Version numbers surfaced to the host (CLI, status, updater).
public enum Versions {
    /// Velox release version.
    public static let velox = "${VELOX_VERSION}"
    /// GitHub repo (owner/name) the updater checks for new releases.
    public static let githubRepo = "${VELOX_GITHUB_REPO}"
    /// Privileged-port-helper revision. The helper is (re)installed (one admin prompt) only when
    /// this changes — not on every Velox update. Bumped in versions.env when the helper changes.
    public static let porthelperRevision = "${PORTHELPER_REVISION}"

    /// Guest kernel version (the VM "OS version") — built from kernel.org source.
    public static let kernelVersion = "${KERNEL_ORG_VERSION}"
    /// Docker Engine version in the guest (Docker's official static release).
    public static let dockerVersion = "${DOCKER_VERSION}"
    /// Ed25519 public key (base64) release .zips are signed with; empty = dev build,
    /// updater signature verification skipped. See VELOX_RELEASE_PUBKEY in versions.env.
    public static let releasePubkey = "${VELOX_RELEASE_PUBKEY:-}"
}
EOF

echo "wrote $OUT (velox ${VELOX_VERSION})"
