#!/usr/bin/env bash
# Generate Sources/Velox/Support/Versions.swift from versions.env.
# Run automatically by build.sh; the generated file is also committed so the
# package always compiles from a clean checkout.
set -euo pipefail
cd "$(dirname "$0")/.."

set -a; . ./versions.env; set +a

OUT="Sources/Velox/Support/Versions.swift"
cat > "$OUT" <<EOF
// GENERATED by Scripts/gen-versions.sh from versions.env — DO NOT EDIT.
// The single source of truth for all version numbers is versions.env.

/// Version numbers surfaced to the host (CLI, status, updater).
enum Versions {
    /// Velox release version.
    static let velox = "${VELOX_VERSION}"
    /// GitHub repo (owner/name) the updater checks for new releases.
    static let githubRepo = "${VELOX_GITHUB_REPO}"

    /// Guest kernel image (the VM "OS version").
    static let kernelImage = "${KERNEL_IMAGE}"
    /// containerd image running in the guest.
    static let containerdImage = "${CONTAINERD_IMAGE}"
    /// Docker Engine (dockerd) image running in the guest.
    static let dockerImage = "${DIND_IMAGE}"
}
EOF

echo "wrote $OUT (velox ${VELOX_VERSION})"
